// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4dy7KIUMVC53bbCoCEBAytQDsUtiXASU',
    appId: '1:877860610923:web:010d2ae54474bc2455222e',
    messagingSenderId: '877860610923',
    projectId: 'trikekoto',
    authDomain: 'trikekoto.firebaseapp.com',
    databaseURL: 'https://trikekoto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trikekoto.firebasestorage.app',
    measurementId: 'G-F38GCG1RCK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSGx6ODL6Xyl81oosKPksvviJO77z_E00',
    appId: '1:877860610923:ios:281ef5ee9a666fd655222e',
    messagingSenderId: '877860610923',
    projectId: 'trikekoto',
    databaseURL: 'https://trikekoto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trikekoto.firebasestorage.app',
    iosClientId: '877860610923-71v2sa789oiu75j0cofkqk9505jc57ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.trikekoto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4dy7KIUMVC53bbCoCEBAytQDsUtiXASU',
    appId: '1:877860610923:web:bf4260dbba102b9155222e',
    messagingSenderId: '877860610923',
    projectId: 'trikekoto',
    authDomain: 'trikekoto.firebaseapp.com',
    databaseURL: 'https://trikekoto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trikekoto.firebasestorage.app',
    measurementId: 'G-S379VKXG4W',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSGx6ODL6Xyl81oosKPksvviJO77z_E00',
    appId: '1:877860610923:ios:281ef5ee9a666fd655222e',
    messagingSenderId: '877860610923',
    projectId: 'trikekoto',
    databaseURL: 'https://trikekoto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trikekoto.firebasestorage.app',
    iosClientId: '877860610923-71v2sa789oiu75j0cofkqk9505jc57ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.trikekoto',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAXyTOY-ou43KMJESLX2Uu7HHvZokruvE',
    appId: '1:877860610923:android:c7e5bf159aa6c24955222e',
    messagingSenderId: '877860610923',
    projectId: 'trikekoto',
    databaseURL: 'https://trikekoto-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trikekoto.firebasestorage.app',
  );

}